NR-52426 Add release toolkit to pipelines and create prerelease
newrelic/newrelic-prometheus-configurator pull request #89
Opened 2022-09-15 14:08 UTC by alvarocabanas

- Adds release toolkit actions to the releaseChart action generating Changelog and Release notes.
 - Adds releaseIntegration pipeline that generates the changelog and creates the next prerelease every wednesday (tentatively).
 - Adds changelog action validation on PR workflow.
 - Release is still not implemented as we need to think how we want it to be.

2022-09-20 07:12 UTC, marcsanmi commented on .github/workflows/releaseChart.yaml
> +          CR_RELEASE_NOTES_FILE: RELEASE-NOTES.md
I'd say it comes from here https://github.com/newrelic/newrelic-prometheus-configurator/pull/89/files#diff-d298aa52ba694a02cd8b34918926b95a30d2ce0c599ed25547c856646507c030R62.

2022-09-21 10:02 UTC, paologallinaharbur commented on .github/workflows/releaseIntegration.yaml
> +    - cron: "0 4 * * 3"
moreover, if many repos are triggered at the same time I would be a bit scared of the result, should we randomize it somehow?

2022-09-21 10:39 UTC, gsanchezgavier requested changes
as we discussed , it would be good to agree on the release flows before changing the pipeline

2022-10-07 09:42 UTC, gsanchezgavier commented
closed in favor of #126

2022-10-07 09:42 UTC, closed without merging